### ISSUE TITLE
Exception at updating project with no obligations

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#1040]
Just during testing of the current master:

1. create a project
2. click update
3. open the project again
4. edit the project
5. add some moderator or other value.
6. click update project.

Exception trace:

```
2020-11-11 21:36:37 ERROR SW360Assert:141 - linked obligtions cannot be empty
org.eclipse.sw360.datahandler.thrift.SW360Exception: null
	at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:128) [datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:94) [datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.ThriftValidate.prepareProjectObligation(ThriftValidate.java:231) [datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.addLinkedObligations(ProjectDatabaseHandler.java:538) [src-common-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.projects.ProjectHandler.addLinkedObligations(ProjectHandler.java:324) [src-projects-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$addLinkedObligations.getResult(ProjectService.java:3592) [datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$addLinkedObligations.getResult(ProjectService.java:3572) [datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) [datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) [datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) [src-common-11.1.0-SNAPSHOT.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-11-11 21:36:37 ERROR ProcessFunction:47 - Internal error processing addLinkedObligations
org.eclipse.sw360.datahandler.thrift.SW360Exception: null
	at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:142) ~[datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:129) ~[datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:94) ~[datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.ThriftValidate.prepareProjectObligation(ThriftValidate.java:231) ~[datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.addLinkedObligations(ProjectDatabaseHandler.java:538) ~[src-common-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.projects.ProjectHandler.addLinkedObligations(ProjectHandler.java:324) ~[src-projects-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$addLinkedObligations.getResult(ProjectService.java:3592) ~[datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$addLinkedObligations.getResult(ProjectService.java:3572) ~[datahandler-11.1.0-SNAPSHOT.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [datahandler-11.1.0-SNAPSHOT.jar:?]

```

**Comment by mcjaeger** [comment]
seems to work now again. (just tested on master)
