### ISSUE TITLE
NullPointer exception is appearing for while generating Report for some projects

### ISSUE THREAD

**Issue by JaideepPalit** [eclipse/sw360#1049]
```
2020-11-24 04:35:01 ERROR ProcessFunction:47 - Internal error processing getLicenseInfoFile
java.lang.NullPointerException: null
    at java.lang.String.replace(String.java:2143) ~[?:?]
    at org.eclipse.sw360.licenseinfo.outputGenerators.DocxUtils.replaceParagraph(DocxUtils.java:128) ~[src-licenseinfo-12.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.licenseinfo.outputGenerators.DocxUtils.replaceAllBodyElements(DocxUtils.java:120) ~[src-licenseinfo-12.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.licenseinfo.outputGenerators.DocxUtils.replaceText(DocxUtils.java:106) ~[src-licenseinfo-12.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.licenseinfo.outputGenerators.DocxGenerator.fillReportDocument(DocxGenerator.java:279) ~[src-licenseinfo-12.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.licenseinfo.outputGenerators.DocxGenerator.generateOutputFile(DocxGenerator.java:132) ~[src-licenseinfo-12.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.licenseinfo.outputGenerators.DocxGenerator.generateOutputFile(DocxGenerator.java:61) ~[src-licenseinfo-12.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.licenseinfo.LicenseInfoHandler.getLicenseInfoFile(LicenseInfoHandler.java:157) ~[src-licenseinfo-12.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.datahandler.thrift.licenseinfo.LicenseInfoService$Processor$getLicenseInfoFile.getResult(LicenseInfoService.java:824) ~[datahandler-12.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.datahandler.thrift.licenseinfo.LicenseInfoService$Processor$getLicenseInfoFile.getResult(LicenseInfoService.java:804) ~[datahandler-12.1.0-SNAPSHOT.jar:?]
    at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [libthrift-0.13.0.jar:0.13.0]
    at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) [libthrift-0.13.0.jar:0.13.0]
    at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) [libthrift-0.13.0.jar:0.13.0]
    at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) [src-common-12.1.0-SNAPSHOT.jar:?]
```

**Comment by neubs-bsi** [comment]
As discussed in dev call: this has been implemented and merged,
