### ISSUE TITLE
Accessing releases of a component does not work

### ISSUE THREAD

**Issue by Lythenas** [eclipse/sw360#1115]
After creating a release for a component it shows up in the "Release Overview" but after clicking on the version number of any release it just shows "Components is temporarily unavailable."

This is what the tomcat log shows:

```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 9
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at org.eclipse.sw360.portal.portlets.components.ComponentPortlet.createFossologyJobViewLink(ComponentPortlet.java:1395)
	at org.eclipse.sw360.portal.portlets.components.ComponentPortlet.prepareReleaseDetailView(ComponentPortlet.java:1339)
	at org.eclipse.sw360.portal.portlets.components.ComponentPortlet.doView(ComponentPortlet.java:639)
	at com.liferay.portal.kernel.portlet.LiferayPortlet.doDispatch(LiferayPortlet.java:286)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:465)
	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:304)
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127)
	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58)
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124)
	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71)
	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:571)
```

We are running Version 13.0.0

**Comment by Lythenas** [comment]
It seems this issue only occurs when Fossology is not configured correctly.

**Comment by mcjaeger** [comment]
hm, I have seen that too, but redeployed and then it did not show up so I was thinking if was a faulty deployment on my side, thanks for the hint with the fossology config!
