### ISSUE TITLE
OAuthClient error when I create new client from UI

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#1175]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

I guess my setting is not property, but can't find reason.

Login authorization/client-management with mail and pass
Try to make client
Return this error and failed to create client

> {
    "readyState": 4,
    "responseText": "",
    "status": 401,
    "statusText": "error"
}

#### How to reproduce

Describe the bug and list the steps you used when the issue occurred.

#### Screenshots
![image](https://user-images.githubusercontent.com/39894802/114651755-83759400-9d1f-11eb-9758-61ff30454b4a.png)

![error0](https://user-images.githubusercontent.com/39894802/114649660-e533ff00-9d1b-11eb-8c81-86d3f04baa8b.png)
![error1](https://user-images.githubusercontent.com/39894802/114649665-e7965900-9d1b-11eb-991e-ba9fcc09693e.png)
![image](https://user-images.githubusercontent.com/39894802/114651693-6771f280-9d1f-11eb-84b9-b8b8437a829a.png)

### Versions

* Version: 13.2.0-SNAPSHOT | Branch: master (d4599a2)
* Operating System (lsb_release -a):
 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

### Logs

![image](https://user-images.githubusercontent.com/39894802/114650483-49a38e00-9d1d-11eb-9d8e-1d69185c7b43.png)

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs
Forwarding to error  occurred when I login  client-management. 
Redirect failed due to my setting?

2021-04-14 03:38:33 ERROR ErrorPageFilter:176 - Forwarding to error page from request [/client-manageme
nt/] due to exception [404 ]
org.springframework.web.client.HttpClientErrorException: 404
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorH
andler.java:78) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700) ~[spring-w
eb-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653) ~[spring-web-4.
3.12.RELEASE.jar:4.3.12.RELEASE]

**Comment by KoukiHama** [comment]
I succeeded get client from sw360 docker image...
 
![Uploading image.png…]()
