### ISSUE TITLE
OAuth Client option missing in UI & Not working for SW360 that uses ldap authentication

### ISSUE THREAD

**Issue by dineshr93** [eclipse/sw360#1191]
### Description
Issue 1
**OAuth Client** option is missing in the admin dropdown UI 

Issue 2
It is not working for Sw360 configured to use LDAP authentication

#### How to reproduce

Issue 1
click the admin drop down 

Issue 2
Configure the sw360 to ldap 
update to sw360-13.2.0-M1 2c776f9
click the admin>Oauth client
we will get the below screen shot

( logging this bug for the future work )
#### Screenshots

Issue 1
![image](https://user-images.githubusercontent.com/4498415/116532373-7391ae80-a8e0-11eb-8a7c-81f62ccf3e84.png)

Issue 2
![image](https://user-images.githubusercontent.com/4498415/116529412-37a91a00-a8dd-11eb-961d-2e9dd017f069.png)

### Versions

* Last commit id on master: sw360-13.2.0-M1 2c776f9
* Operating System (lsb_release -a): 18.04.5 LTS (GNU/Linux 4.15.0-121-generic x86_64)

#### Tomcat logs

Below is the initial error we get regularily even before this update during the sw360 login step. Inspite of this error, tool can able to login via ldap user credentials successfully.  

```
2021-04-29 09:39:27.184 WARN  [http-nio-8080-exec-2][PortalImpl:1036] Redirect URL http://usw360_url.com:8080/web/guest/home?p_p_id=com_liferay_login_web_portlet_LoginPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_state_rcv=1&refererPlid=27 is not allowed
2021-04-29 09:39:31.219 ERROR [http-nio-8080-exec-3][LDAPAuth:455] Problem accessing LDAP server
java.lang.NullPointerException
        at com.liferay.portal.security.ldap.internal.exportimport.LDAPUserImporterImpl.importGroups(LDAPUserImporterImpl.java:1033)
        at com.liferay.portal.security.ldap.internal.exportimport.LDAPUserImporterImpl.importUser(LDAPUserImporterImpl.java:190)
        at com.liferay.portal.security.ldap.internal.authenticator.LDAPAuth.authenticate(LDAPAuth.java:384)
        at com.liferay.portal.security.ldap.internal.authenticator.LDAPAuth.authenticateAgainstPreferredLDAPServer(LDAPAuth.java:590)
        at com.liferay.portal.security.ldap.internal.authenticator.LDAPAuth.authenticate(LDAPAuth.java:493)
        at com.liferay.portal.security.ldap.internal.authenticator.LDAPAuth.authenticateByEmailAddress(LDAPAuth.java:99)
        at com.liferay.portal.security.auth.AuthPipeline._authenticate(AuthPipeline.java:146)
        at com.liferay.portal.security.auth.AuthPipeline.authenticateByEmailAddress(AuthPipeline.java:39)
        at com.liferay.portal.service.impl.UserLocalServiceImpl.authenticate(UserLocalServiceImpl.java:5517)
        at com.liferay.portal.service.impl.UserLocalServiceImpl.authenticateByEmailAddress(UserLocalServiceImpl.java:1257)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66)
        at com.sun.proxy.$Proxy825.authenticateByEmailAddress(Unknown Source)
        at com.liferay.portal.kernel.service.UserLocalServiceWrapper.authenticateByEmailAddress(UserLocalServiceWrapper.java:439)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66)
        at com.sun.proxy.$Proxy826.authenticateByEmailAddress(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
        at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
        at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
        at com.sun.proxy.$Proxy67.authenticateByEmailAddress(Unknown Source)
        at com.liferay.portal.kernel.service.UserLocalServiceUtil.authenticateByEmailAddress(UserLocalServiceUtil.java:437)
        at com.liferay.portal.security.auth.session.AuthenticatedSessionManagerImpl._getAuthenticatedUser(AuthenticatedSessionManagerImpl.java:493)
        at com.liferay.portal.security.auth.session.AuthenticatedSessionManagerImpl.login(AuthenticatedSessionManagerImpl.java:137)
        at com.liferay.login.web.internal.portlet.action.LoginMVCActionCommand.login(LoginMVCActionCommand.java:209)
        at com.liferay.login.web.internal.portlet.action.LoginMVCActionCommand.doProcessAction(LoginMVCActionCommand.java:99)
        at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:61)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callActionMethod(MVCPortlet.java:358)
        at com.liferay.portal.kernel.portlet.LiferayPortlet.processAction(LiferayPortlet.java:88)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.processAction(MVCPortlet.java:248)
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:77)
        at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:50)
        at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
        at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
        at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:571)
        at com.liferay.portlet.internal.InvokerPortletImpl.invokeAction(InvokerPortletImpl.java:611)
        at com.liferay.portlet.internal.InvokerPortletImpl.processAction(InvokerPortletImpl.java:286)
        at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.processAction(MonitoringInvokerPortlet.java:195)
        at com.liferay.portlet.internal.PortletContainerImpl._processAction(PortletContainerImpl.java:521)
        at com.liferay.portlet.internal.PortletContainerImpl.lambda$processAction$0(PortletContainerImpl.java:148)
        at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:425)
        at com.liferay.portlet.internal.PortletContainerImpl.processAction(PortletContainerImpl.java:141)
        at com.liferay.portlet.SecurityPortletContainerWrapper.processAction(SecurityPortletContainerWrapper.java:91)
        at com.liferay.portlet.RestrictPortletContainerWrapper.processAction(RestrictPortletContainerWrapper.java:72)
        at com.liferay.portal.kernel.portlet.PortletContainerUtil.processAction(PortletContainerUtil.java:117)
        at com.liferay.portal.action.LayoutAction.processLayout(LayoutAction.java:347)
        at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:170)
        at com.liferay.portal.struts.PortalRequestProcessor._process(PortalRequestProcessor.java:414)
        at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:154)
        at com.liferay.portal.internal.servlet.MainServlet.doPost(MainServlet.java:214)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at com.liferay.portal.internal.servlet.MainServlet.service(MainServlet.java:621)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124)
        at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.servlet.filters.lockout.LockoutFilter.processFilter(LockoutFilter.java:58)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.servlet.filters.secure.BaseAuthFilter.processFilter(BaseAuthFilter.java:340)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.monitoring.internal.servlet.filter.MonitoringFilter.processFilter(MonitoringFilter.java:183)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:104)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
        at com.liferay.friendly.url.internal.servlet.FriendlyURLServlet.service(FriendlyURLServlet.java:463)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at com.liferay.portal.servlet.ServletAdapter.service(ServletAdapter.java:99)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.servlet.filters.i18n.I18nFilter.processFilter(I18nFilter.java:368)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.servlet.filters.lockout.LockoutFilter.processFilter(LockoutFilter.java:58)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.servlet.filters.secure.BaseAuthFilter.processFilter(BaseAuthFilter.java:340)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.servlet.filters.etag.ETagFilter.processFilter(ETagFilter.java:87)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.servlet.filters.autologin.AutoLoginFilter.processFilter(AutoLoginFilter.java:264)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.sharepoint.SharepointFilter.processFilter(SharepointFilter.java:88)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.processFilter(VirtualHostFilter.java:250)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.monitoring.internal.servlet.filter.MonitoringFilter.processFilter(MonitoringFilter.java:183)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
        at com.liferay.portal.servlet.filters.urlrewrite.UrlRewriteFilter.processFilter(UrlRewriteFilter.java:65)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:175)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:175)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:104)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by KoukiHama** [comment]
> Issue 1
> OAuth Client option is missing in the admin dropdown UI

Did you re-import new lar file? Latest lar file is necessary for the UI.

https://github.com/eclipse/sw360/pull/1140#issue-592819445

**Comment by dineshr93** [comment]
Hi @KoukiHama 

I updated the lar . Now I can see the option. 

Image 1
![image](https://user-images.githubusercontent.com/4498415/116552847-c9bf1b80-a8f9-11eb-900a-c276c262d9be.png)

But when i click it I get below (loading for 1 sec) 

Image 2
![image](https://user-images.githubusercontent.com/4498415/116552584-7d73db80-a8f9-11eb-8d43-def3f180f2af.png)

and moves to 3rd image

Image 3
![image](https://user-images.githubusercontent.com/4498415/116552644-8c5a8e00-a8f9-11eb-9347-cf965f981ed6.png)

When I reload same happends Image2 & Image3

I restarted the tomcat server the problem remains the same

**Comment by KoukiHama** [comment]
@dineshr93 
Hello,
Did you set sw360.properties  like this?

https://github.com/eclipse/sw360/blob/ebcbf40b5b95b03429d0a734d8df6da3379d809e/scripts/docker-config/etc_sw360/sw360.properties#L11

https://github.com/eclipse/sw360/blob/ebcbf40b5b95b03429d0a734d8df6da3379d809e/scripts/docker-config/etc_sw360/sw360.properties#L13

**Comment by dineshr93** [comment]
Hi @KoukiHama 
Thanks for the reply.

My sw360.properties looks like below 

```
backend.url= http://localhost:8080
## API Token generation sw360.properties
rest.apitoken.generator.enable=true
rest.apitoken.read.validity.days=90
rest.apitoken.write.validity.days=30
rest.apitoken.hash.salt=$2b$04$Software360RestApiSalt
```

The missing entry is **sw360.liferay.company.id=20098** 

I have added it and started back the server. But the problem is still there..  (no log is generated too)

![oauth](https://user-images.githubusercontent.com/4498415/129369009-4f7363f7-42c5-490b-856e-94118d1661ee.gif)

**Comment by KoukiHama** [comment]
Your account seems to fails to get client id of api due to ldap setting. 

Can your accounts get to client id or tokens through commands lines?

**Comment by dineshr93** [comment]
@KoukiHama  I have not tried the command line way. But the API works fine.  is there any simple commands there to test ?

**Comment by KoukiHama** [comment]
@dineshr93 

for example, you can do test about Token request.

> > curl
>     -X POST
>     --user 'client-id:client-secret'
>     -d 'grant_type=password&username=<USERNAME>&password=<PASSWORD>' https://sw360.org/authorization/oauth/token -k

And, I guess you may make some mistakes in /etc/sw360/authorization/application.yml
https://github.com/eclipse/sw360/wiki/Deploy-Configuration-Files#authorizationapplicationyml-etcsw360authorizationapplicationyml

**Comment by meeraa247** [comment]
Hey @all, 

we have been experiencing the same behavior with regards to the API / Rest Components. We also double checked the config(s) in /etc/sw360 etc. Is there anything else we could do to track this down ?

**Comment by dineshr93** [comment]
> Hi @KoukiHama
> 
> I updated the lar . Now I can see the option.
> 
> Image 1 ![image](https://user-images.githubusercontent.com/4498415/116552847-c9bf1b80-a8f9-11eb-900a-c276c262d9be.png)
> 
> But when i click it I get below (loading for 1 sec)
> 
> Image 2 ![image](https://user-images.githubusercontent.com/4498415/116552584-7d73db80-a8f9-11eb-8d43-def3f180f2af.png)
> 
> and moves to 3rd image
> 
> Image 3 ![image](https://user-images.githubusercontent.com/4498415/116552644-8c5a8e00-a8f9-11eb-9347-cf965f981ed6.png)
> 
> When I reload same happends Image2 & Image3
> 
> I restarted the tomcat server the problem remains the same
The updated url is 
https://www.eclipse.org/sw360/docs/deployment/deploy-configuration-files/#authorizationapplicationyml-etcsw360authorizationapplicationyml

**Comment by dineshr93** [comment]
> @dineshr93
> 
> for example, you can do test about Token request.
> 
> > > curl
> > > -X POST
> > > --user 'client-id:client-secret'
> > > -d 'grant_type=password&username=&password=' https://sw360.org/authorization/oauth/token -k
> 
> And, I guess you may make some mistakes in /etc/sw360/authorization/application.yml https://github.com/eclipse/sw360/wiki/Deploy-Configuration-Files#authorizationapplicationyml-etcsw360authorizationapplicationyml

The url is moved to https://www.eclipse.org/sw360/docs/deployment/deploy-configuration-files/#authorizationapplicationyml-etcsw360authorizationapplicationyml
