### ISSUE TITLE
Component tab fail on clean installation of 13.4.0-M1

### ISSUE THREAD

**Issue by heliocastro** [eclipse/sw360#1389]
On complete clean installation, with only admin user ( non default admin name ), component tab simply crash.

Detaild of the build:
Ubuntu 20.04
Couchdb 3.1.1
OpenJDK 11
Postgresql 13
liferay-ce-portal-tomcat-7.3.3-ga4-20200701015330959.tar.gz

The cut down output of stacktrace:
```
   at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doView(MVCPortlet.java:176)
   at org.eclipse.sw360.portal.portlets.Sw360Portlet.doView(Sw360Portlet.java:97)
   at org.eclipse.sw360.portal.portlets.components.ComponentPortlet.doView(ComponentPortlet.java:679)
```

Link for the full log
[sw360.log](https://heliocastro.info/files/sw360.log)

**Comment by heliocastro** [comment]
Easy misleading on the wiki deployment lead to wrong bug.
Is a user with no proper group is assigned ( i.e. Setup user ) try to access components area, it fails, but other tabs work, and then mislead for an invalid issue in sw360 software itself
