### ISSUE TITLE
Liferay Upgrade issue while deployment

### ISSUE THREAD

**Issue by JaideepPalit** [eclipse/sw360#1507]
```
java.lang.RuntimeException: com.liferay.portal.kernel.deploy.auto.AutoDeployException: com.liferay.portal.kernel.deploy.auto.AutoDeployException: org.eclipse.sw360.liferay-theme.war does not support this version of Liferay
	at com.liferay.portal.osgi.web.wab.generator.internal.processor.WabProcessor.executeAutoDeployers(WabProcessor.java:159) ~[?:?]
	at com.liferay.portal.osgi.web.wab.generator.internal.processor.WabProcessor._autoDeploy(WabProcessor.java:177) ~[?:?]
	at com.liferay.portal.osgi.web.wab.generator.internal.processor.WabProcessor.getProcessedFile(WabProcessor.java:119) ~[?:?]
	at com.liferay.portal.osgi.web.wab.generator.internal.WabGenerator.generate(WabGenerator.java:88) ~[?:?]
	at com.liferay.portal.osgi.web.wab.generator.internal.connection.WabURLConnection.getInputStream(WabURLConnection.java:102) ~[?:?]
	at java.net.URL.openStream(URL.java:1165) ~[?:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._install(DirectoryWatcher.java:676) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._install(DirectoryWatcher.java:705) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1008) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:221) [bundleFile:?]
Caused by: com.liferay.portal.kernel.deploy.auto.AutoDeployException: com.liferay.portal.kernel.deploy.auto.AutoDeployException: org.eclipse.sw360.liferay-theme.war does not support this version of Liferay
	at com.liferay.portal.tools.deploy.BaseAutoDeployer.autoDeploy(BaseAutoDeployer.java:247) ~[portal-impl.jar:?]
	at com.liferay.portal.deploy.auto.ThemeAutoDeployer.autoDeploy(ThemeAutoDeployer.java:95) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.deploy.auto.BaseAutoDeployListener.deploy(BaseAutoDeployListener.java:47) ~[portal-kernel.jar:?]
	at com.liferay.portal.osgi.web.wab.generator.internal.processor.WabProcessor.executeAutoDeployers(WabProcessor.java:156) ~[?:?]
	... 9 more
Caused by: com.liferay.portal.kernel.deploy.auto.AutoDeployException: org.eclipse.sw360.liferay-theme.war does not support this version of Liferay
	at com.liferay.portal.tools.deploy.BaseAutoDeployer.autoDeploy(BaseAutoDeployer.java:143) ~[portal-impl.jar:?]
	at com.liferay.portal.deploy.auto.ThemeAutoDeployer.autoDeploy(ThemeAutoDeployer.java:95) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.deploy.auto.BaseAutoDeployListener.deploy(BaseAutoDeployListener.java:47) ~[portal-kernel.jar:?]
	at com.liferay.portal.osgi.web.wab.generator.internal.processor.WabProcessor.executeAutoDeployers(WabProcessor.java:156) ~[?:?]
	... 9 more
```

```
2022-04-13 06:47:33.380 ERROR [Framework Event Dispatcher: Equinox Container: 5203c67f-5e34-46bd-a360-cc3a56d15ca8][Framework:93] FrameworkEvent ERROR 
com.liferay.portal.kernel.log.LogSanitizerException: org.osgi.framework.BundleException: Could not resolve module: sw360-portlet [1508]_  Unresolved requirement: Import-Package: com.liferay.expando.kernel.model; version="[3.3.0,4.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
2022-04-13 06:47:33.442 ERROR [main][DirectoryWatcher:1173] Unable to start bundle: file:/home/jai/Desktop/project/liferay-ce-portal-7.4.3.18-ga18/osgi/modules/org.eclipse.sw360.portlet-15.1.0-SNAPSHOT.jar
com.liferay.portal.kernel.log.LogSanitizerException: org.osgi.framework.BundleException: Could not resolve module: sw360-portlet [1508]_  Unresolved requirement: Import-Package: com.liferay.expando.kernel.model; version="[3.3.0,4.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1156) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1189) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:1130) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1041) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher.start(DirectoryWatcher.java:264) [bundleFile:?]
	at com.liferay.portal.file.install.internal.activator.FileInstallImplBundleActivator.start(FileInstallImplBundleActivator.java:107) [bundleFile:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1) [org.eclipse.osgi.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1002) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:354) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.Module.doStart(Module.java:581) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.Module.start(Module.java:449) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447) [org.eclipse.osgi.jar:?]
	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._startDynamicBundles(ModuleFrameworkImpl.java:1628) [com.liferay.portal.bootstrap.jar:?]
	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:250) [com.liferay.portal.bootstrap.jar:?]
	at com.liferay.portal.module.framework.ModuleFrameworkUtil.startFramework(ModuleFrameworkUtil.java:45) [portal-impl.jar:?]
	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:286) [portal-impl.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.liferay.shielded.container.internal.proxy.ContextClassLoaderInvocationHandler.invoke(ContextClassLoaderInvocationHandler.java:43) [com.liferay.shielded.container.impl.jar:?]
	at com.liferay.shielded.container.internal.proxy.EventListenerInvocationHandler.invoke(EventListenerInvocationHandler.java:64) [com.liferay.shielded.container.impl.jar:?]
	at com.sun.proxy.$Proxy5.contextInitialized(Unknown Source) [?:?]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4766) [catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230) [catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.56]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726) [catalina.jar:9.0.56]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698) [catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696) [catalina.jar:9.0.56]
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:690) [catalina.jar:9.0.56]
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1889) [catalina.jar:9.0.56]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.56]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118) [?:?]
	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:583) [catalina.jar:9.0.56]
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:473) [catalina.jar:9.0.56]
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618) [catalina.jar:9.0.56]
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319) [catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) [catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) [catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) [catalina.jar:9.0.56]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946) [catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835) [catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.56]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396) [catalina.jar:9.0.56]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386) [catalina.jar:9.0.56]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.56]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) [?:?]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919) [catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263) [catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432) [catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927) [catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.56]
	at org.apache.catalina.startup.Catalina.start(Catalina.java:772) [catalina.jar:9.0.56]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345) [bootstrap.jar:9.0.56]
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476) [bootstrap.jar:9.0.56]
2022-04-13 06:47:33.446 INFO  [main][ModuleFrameworkImpl:1667] Started web bundles
2022-04-13 06:47:33.446 INFO  [main][ModuleFrameworkImpl:253] Navigate to Control Panel > System > Gogo Shell and enter "lb" to see all bundles
2022-04-13 06:47:33.474 ERROR [fileinstall-directory-watcher][DirectoryWatcher:1173] Unable to start bundle: file:/home/jai/Desktop/project/liferay-ce-portal-7.4.3.18-ga18/osgi/modules/org.eclipse.sw360.portlet-15.1.0-SNAPSHOT.jar
com.liferay.portal.kernel.log.LogSanitizerException: org.osgi.framework.BundleException: Could not resolve module: sw360-portlet [1508]_  Unresolved requirement: Import-Package: com.liferay.expando.kernel.model; version="[3.3.0,4.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1156) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1189) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:1130) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1041) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:221) [bundleFile:?]
2022-04-13 06:47:36.151 WARN  [main][SidecarManager:103] Liferay automatically starts a child process of Elasticsearch named sidecar for convenient development and demonstration purposes. Do NOT use sidecar in production. Refer to the documentation for details on the limitations of sidecar and instructions on configuring a remote Elasticsearch connection in the Control Panel.
2022-04-13 06:47:47.099 INFO  [main][Sidecar:119] Sidecar Elasticsearch liferay started at 127.0.0.1:9201
```

**Comment by JaideepPalit** [comment]
Hi @akapti ,

Kindly refer - https://github.com/eclipse/sw360/pull/1508

**Comment by JaideepPalit** [comment]
```
java.lang.RuntimeException: com.liferay.portal.kernel.deploy.auto.AutoDeployException: com.liferay.portal.kernel.deploy.auto.AutoDeployException: org.eclipse.sw360.liferay-theme.war does not support this version of Liferay
	at com.liferay.portal.osgi.web.wab.generator.internal.processor.WabProcessor.executeAutoDeployers(WabProcessor.java:159) ~[?:?]
```
-Fixed

**Comment by akapti** [comment]
> Import-Package: com.liferay.expando.kernel.model; version="[3.3.0,4.0.0)"_ [Sanitized]

To fix the above issue, Can you try updating the `liferay.portal.kernel.version` in `pom.xml` from `8.1.0` to current Liferay `7.4.3.18` kernel version?
You can find the portal kernel version in Manifest file of `/liferay-ce-portal-7.4.4.18-ga18/tomcat-9.0.56/webapps/ROOT/WEB-INF/shielded-container-lib/portal-kernel.jar`.

Screenshot for reference only, (this is not the exact kernel version of liferay 7.4.3.18):
![image](https://user-images.githubusercontent.com/50870174/163230312-6ed99ac3-8210-4830-a218-e5463e618cc4.png)


I cannot guarantee that it will fix the issue, But you can give it a try.
