### ISSUE TITLE
I registered the component and entered the CPE but cannot get the vulnerability from "https://cve.circl.lu/".

### ISSUE THREAD

**Issue by yyosioka** [eclipse/sw360#1512]
### Description

I registered the component and entered the CPE but cannot get the vulnerability from "https://cve.circl.lu/".

Is it a specification that vulnerabilities cannot be retrieved from "https://cve.circl.lu/"? Or do I need a different setup?

#### How to reproduce

No1 The environment was constructed with reference to the following page.
https://github.com/eclipse/sw360/blob/master/README_DOCKER.md

No2 SW360 is up and running.
docker-compose up

No3 Enter the sw360 docker.
docker exec -it xxxxxx /bin/bash

No4  Edit the following files with the following values
[File]
/app/sw360/tomcat-9.0.33/webapps/schedule/WEB-INF/classes/sw360.properties

[value]
schedule.cvesearch.interval.seconds = 300
autostart = cvesearchService

No5 Restart Docker
docker-compose down
doker-compose up

No6 Enter component and CPE values

### Versions

2022/4/7 latest acquisition

#### SW360 logs
2022-04-15 04:50:00 INFO  CveSearchHandler:133 - Starting CveSearch update...
2022-04-15 04:50:00 ERROR Heuristic:53 - IOException in searchlevel
	with description=CPE
	with needle=cpe:2.3:.:.*apache.*maven.*3.0.4.*
	with exception message=https://cve.circl.lu/api/cvefor/cpe%3A2.3%3A.%3A.*apache.*maven.*3.0.4.*
java.io.FileNotFoundException: https://cve.circl.lu/api/cvefor/cpe%3A2.3%3A.%3A.*apache.*maven.*3.0.4.*
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250) ~[?:?]
	at java.net.URL.openStream(URL.java:1165) ~[?:?]
	at org.eclipse.sw360.cvesearch.datasource.CveSearchApiImpl.getParsedContentFor(CveSearchApiImpl.java:53) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.cvesearch.datasource.CveSearchApiImpl.getParsedCveSearchDatas(CveSearchApiImpl.java:69) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.cvesearch.datasource.CveSearchApiImpl.cvefor(CveSearchApiImpl.java:104) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.cvesearch.datasource.heuristics.Heuristic.runForNeedleWithMeta(Heuristic.java:47) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
	at java.util.Collections$2.tryAdvance(Collections.java:4747) ~[?:?]
	at java.util.Collections$2.forEachRemaining(Collections.java:4755) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.eclipse.sw360.cvesearch.datasource.heuristics.Heuristic.lambda$run$2(Heuristic.java:66) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:199) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543) ~[?:?]
	at org.eclipse.sw360.cvesearch.datasource.heuristics.Heuristic.run(Heuristic.java:68) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.cvesearch.datasource.CveSearchWrapper.searchForRelease(CveSearchWrapper.java:37) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.cvesearch.service.CveSearchHandler.updateForRelease(CveSearchHandler.java:62) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553) [?:?]
	at org.eclipse.sw360.cvesearch.service.CveSearchHandler.fullUpdate(CveSearchHandler.java:127) [src-cvesearch-15.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.cvesearch.service.CveSearchHandler.update(CveSearchHandler.java:134) [src-cvesearch-15.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.cvesearch.CveSearchService$Processor$update.getResult(CveSearchService.java:584) [datahandler-15.1.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.cvesearch.CveSearchService$Processor$update.getResult(CveSearchService.java:564) [datahandler-15.1.0-SNAPSHOT.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [libthrift-0.14.0.jar:0.14.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) [libthrift-0.14.0.jar:0.14.0]
	at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) [libthrift-0.14.0.jar:0.14.0]
	at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) [src-common-15.1.0-SNAPSHOT.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by KoukiHama** [comment]
#1411 is same.
CVE service https://cve.circl.lu/ does not work now, so  you need to use https://cvepremium.circl.lu/

**Comment by yyosioka** [comment]
@KoukiHama 
Thanks for the information.

We have confirmed that the vulnerability can be obtained by going inside 
SW360Docker and editing the values in the following file.
[File]
/app/sw360/tomcat-9.0.33/webapps/cvesearch/WEB-INF/classes/cvesearch.properties

[value]
cvesearch.host=https://cve.circl.lu/ 
↓
cvesearch.host=https://cvepremium.circl.lu

Then restart Docker.

I have confirmed that this is the same case as #1411.
This case is closed as there is no need to manage duplicates.
