### ISSUE TITLE
Search Link Project show some private project

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#1522]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

When user search other project for linking project, user can see private project in the dialog box.
(Error is Same with this. https://github.com/eclipse/sw360/pull/1468#issuecomment-1084156246)

#### How to reproduce

Make project as private project,  login admin user and use dialog box for linking project.

#### Screenshots

![image](https://user-images.githubusercontent.com/39894802/167768441-5d0a15dd-b6a1-46b7-bedd-c58efc2e7b72.png)

### Versions

* Last commit id on master: 3f8323a
* Operating System (lsb_release -a):

### Logs

sw360_1           | 2022-05-10 02:34:59 ERROR SW360Assert:135 - User: admin1@sw360.org is not allowed to view the requested project: 7ab3b52f03fc4b229f06b8275b6ca05d
sw360_1           | org.eclipse.sw360.datahandler.thrift.SW360Exception: null
sw360_1           |     at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:134) [datahandler-15.1.0-SNAPSHOT.jar:?]
sw360_1           |     at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.getProjectById(ProjectDatabaseHandler.java:282) [src-common-15.1.0-SNAPSHOT.jar:?]
sw360_1           |     at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.getProjectForEdit(ProjectDatabaseHandler.java:886) [src-common-15.1.0-SNAPSHOT.jar:?]
sw360_1           |     at org.eclipse.sw360.projects.ProjectHandler.getProjectByIdForEdit(ProjectHandler.java:207) [src-projects-15.1.0-SNAPSHOT.jar:?]
sw360_1           |     at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$getProjectByIdForEdit.getResult(ProjectService.java:3866) [datahandler-15.1.0-SNAPSHOT.jar:?]
sw360_1           |     at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$getProjectByIdForEdit.getResult(ProjectService.java:3845) [datahandler-15.1.0-SNAPSHOT.jar:?]
sw360_1           |     at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [datahandler-15.1.0-SNAPSHOT.jar:?]
sw360_1           |     at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) [datahandler-15.1.0-SNAPSHOT.jar:?]
sw360_1           |     at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) [datahandler-15.1.0-SNAPSHOT.jar:?]
sw360_1           |     at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) [src-common-15.1.0-SNAPSHOT.jar:?]
sw360_1           |     at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
sw360_1           |     at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
sw360_1           |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.33]
sw360_1           |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360_1           |     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.33]
sw360_1           |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360_1           |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360_1           |     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
sw360_1           |     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
sw360_1           |     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
sw360_1           |     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
sw360_1           |     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
sw360_1           |     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
sw360_1           |     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
sw360_1           |     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
sw360_1           |     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
sw360_1           |     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
sw360_1           |     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
sw360_1           |     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
sw360_1           |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
sw360_1           |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
sw360_1           |     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
sw360_1           |     at java.lang.Thread.run(Thread.java:829) [?:?]

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by KoukiHama** [comment]
If user select this restricted (private) Project, this error massage show in dialog.
![image](https://user-images.githubusercontent.com/39894802/167769823-6f8b5aa7-8b14-4d22-aacc-239343c21362.png)

Note: lack of filtering in ProjectSearchHandler.search
