### ISSUE TITLE
migrating script error while running 048_add_component_businessunit.py from 13.4.0 to 15.0.0

### ISSUE THREAD

**Issue by dineshr93** [eclipse/sw360#1821]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

While executing the script 048

i get this error while migrating script is run from 13.4.0 to 15.0.0

https://github.com/eclipse/sw360/issues/1500#issuecomment-1331872514

https://github.com/eclipse/sw360/blob/main/scripts/migrations/048_add_component_businessunit.py

```
/appsrc/sw360/scripts/migrations$ sudo python 048_add_component_businessunit.py

Add a business unit field to the component and set the creator organization.
Found 753 components in db!
Traceback (most recent call last):
  File "048_add_component_businessunit.py", line 129, in <module>
    run()
  File "048_add_component_businessunit.py", line 98, in run
    creator = component['createdBy']
KeyError: 'createdBy'

```

#### How to reproduce

Describe the bug and list the steps you used when the issue occurred.

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by dineshr93** [comment]
Solved this due to mis config of username and pwd

**Comment by dineshr93** [comment]
Hi @KoukiHama  

I set the username and password for couchdb 
and curl command works properly
I get again the below error while running migrating script 48https://github.com/eclipse/sw360/blob/main/scripts/migrations/048_add_component_businessunit.py

May i have your help?

```
/appsrc/sw360/scripts/migrations$ sudo python 048_add_component_businessunit.py

Add a business unit field to the component and set the creator organization.
Found 753 components in db!
Traceback (most recent call last):
  File "048_add_component_businessunit.py", line 129, in <module>
    run()
  File "048_add_component_businessunit.py", line 98, in run
    creator = component['createdBy']
KeyError: 'createdBy'
```

**Comment by KoukiHama** [comment]
Which version python and pip did you use?

**Comment by dineshr93** [comment]
> Which version python and pip did you use?

Python 2.7.17

**Comment by dineshr93** [comment]
Also I have couch db version 2.1.2
```
 curl http://localhost:5984 | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   116  100   116    0     0  38666      0 --:--:-- --:--:-- --:--:-- 38666
{
   "features" : [
      "scheduler"
   ],
   "couchdb" : "Welcome",
   "version" : "2.1.2",
   "vendor" : {
      "name" : "The Apache Software Foundation"
   }
}

```

**Comment by KoukiHama** [comment]
oh...
I recommend to update couchdb  version 3.2 at first. 

python version is ok for the scripts.

and did you install couchdb library?

> pip install couchdb

**Comment by dineshr93** [comment]
> oh... I recommend to update couchdb version 3.2 at first.
> 
> python version is ok for the scripts.
> 
> and did you install couchdb library?
> 
> > pip install couchdb

yes. I have did pip install couchdb 

Is there any guide to upgrade couchdb from 2.2 to 3.2.2 ?
I am afraid its a production server and data will get loss

**Comment by KoukiHama** [comment]
https://docs.couchdb.org/en/stable/install/upgrading.html

when i updated couchdb version, i used official document.

https://docs.couchdb.org/en/stable/maintenance/backups.html


this is helpful for backup before doingupdate

**Comment by dineshr93** [comment]
> https://docs.couchdb.org/en/stable/install/upgrading.html
> 
> when i updated couchdb version, i used official document.
> 
> https://docs.couchdb.org/en/stable/maintenance/backups.html
> 
> this is also helpful for backup before doing update

Hi @KoukiHama 

I installed couchdb version 3.3.1

And tried to run the script again

sudo python 048_add_component_businessunit.py

It threw this error again
```
Add a business unit field to the component and set the creator organization.
Found 753 components in db!
Traceback (most recent call last):
  File "048_add_component_businessunit.py", line 129, in <module>
    run()
  File "048_add_component_businessunit.py", line 98, in run
    creator = component['createdBy']
KeyError: 'createdBy'

```

**Comment by KoukiHama** [comment]
did you change option in python file of Line 27.
Dry rum option need to be false.

**Comment by dineshr93** [comment]
> Did you change option in python file of Line 28? Dry run option need to be false.
> 
> Original Setting is true.

@KoukiHama 
I changes and tried. But got Same error
```

sudo python 048_add_component_businessunit.py
Add a business unit field to the component and set the creator organization.
Found 753 components in db!
Traceback (most recent call last):
  File "048_add_component_businessunit.py", line 129, in <module>
    run()
  File "048_add_component_businessunit.py", line 98, in run
    creator = component['createdBy']
KeyError: 'createdBy'

```

**Comment by dineshr93** [comment]
Hi @KoukiHama  I found the cause of the problem , I inspected the database

for one component this field is indeed missing thats why it is throwing this error. My question is can I skip this component and move forward ?. Will there be any error during in the UI display ?

**Comment by KoukiHama** [comment]
one question, is this the first time to use the scripts for the instance.

I think of this comment.

https://github.com/eclipse/sw360/issues/1500#issuecomment-1331945592

**Comment by dineshr93** [comment]
> One question, is this the first time to use the scripts for the instance ?
> 
> I think of this comment.
> 
> [#1500 (comment)](https://github.com/eclipse/sw360/issues/1500#issuecomment-1331945592)

I have done previously in our test instance. It worked fine. Now I am doing it in production server and found this error

**Comment by dineshr93** [comment]
@KoukiHama  It worked successfully after altering the script . I have raised the pull request to avoid this error.

Also In couchdb moving from 2.2 tpo 3.3.1 we need to mandatorily set the admin user. (https://docs.couchdb.org/en/stable/config/auth.html#admins)

So I had to edit their local.ini file 

To check status 
systemctl status couchdb
To start

systemctl start couchdb  (from couchdb it is mandatory to have admin user and password) local.ini file
