### ISSUE TITLE
SW360 not working after update from 15.0.0-M1 to 16.0.0-M1

### ISSUE THREAD

**Issue by AnkitKumar-786** [eclipse/sw360#1835]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

SW360 not working after update from 15.0.0-M1 to 16.0.0-M1

### Versions

* Last commit id on master: 16.0.0-M1
* Operating System (lsb_release -a): 18.04.5 LTS

### Logs

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Config data location 'file:/etc/sw360/rest/' does not exist

Action:

Check that the value 'file:/etc/sw360/rest/' is correct, or prefix it with 'optional:'

10-Feb-2023 09:04:38.682 SEVERE [main] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/opt/liferay-ce-portal-7.3.3-ga4/tomcat-9.0.33/webapps/resource.war]
        java.lang.IllegalStateException: Error starting child
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
                at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
                at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
                at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
                at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
                at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
                at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
                at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
                at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
        Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/resource]]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
                ... 37 more
        Caused by: org.springframework.boot.context.config.ConfigDataLocationNotFoundException: Config data location 'file:/etc/sw360/rest/' cannot be found
                at org.springframework.boot.context.config.ConfigDataEnvironment.checkMandatoryLocations(ConfigDataEnvironment.java:383)
                at org.springframework.boot.context.config.ConfigDataEnvironment.applyToEnvironment(ConfigDataEnvironment.java:326)
                at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:233)
                at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
                at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
                at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102)
                at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
                at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
                at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
                at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
                at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
                at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
                at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
                at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
                at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
                at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
                at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
                at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:344)
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
                at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:175)
                at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:155)
                at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:97)
                at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5140)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                ... 38 more
2023-02-10 09:04:46 ERROR LoggingFailureAnalysisReporter:40 -

```

**Comment by hoangnt2** [comment]
You are missing sw360 folder in /etc
You can refer to [](https://github.com/eclipse/sw360/tree/sw360-16.0.0-M1/scripts/docker-config/etc_sw360)

**Comment by dineshr93** [comment]
Hi @hoangnt2 
Thank you!
I solved the problem. But I get new Error on with dependencies mismatch. 

```
2023-02-10 13:44:33.267 ERROR [Framework Event Dispatcher: Equinox Container: a96acafa-50ce-4ea7-8214-5b17f492173b][Framework:93] FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: sw360-common-io [1635]_  Unresolved requirement: Import-Package: com.google.common.collect; version="[31.0.0,32.0.0)"_    -> Export-Package: com.google.common.collect; bundle-symbolic-name="sw360-datahandler"; bundle-version="1.0.0"; version="31.0.1"; uses:="com.google.common.base"_       sw360-datahandler [1636]_         Unresolved requirement: Import-Package: com.fasterxml.jackson.annotation; version="[2.13.0,3.0.0)"_  Unresolved requirement: Import-Package: com.google.common.base; version="[31.0.0,32.0.0)"_    -> Export-Package: com.google.common.base; bundle-symbolic-name="sw360-datahandler"; bundle-version="1.0.0"; version="31.0.1"_ [Sanitized]
        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
2023-02-10 13:44:33.271 ERROR [Framework Event Dispatcher: Equinox Container: a96acafa-50ce-4ea7-8214-5b17f492173b][Framework:93] FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: sw360-datahandler [1636]_  Unresolved requirement: Import-Package: com.fasterxml.jackson.annotation; version="[2.13.0,3.0.0)"_ [Sanitized]
        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
2023-02-10 13:44:33.272 ERROR [Framework Event Dispatcher: Equinox Container: a96acafa-50ce-4ea7-8214-5b17f492173b][Framework:93] FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: sw360-exporters [1637]_  Unresolved requirement: Import-Package: com.google.common.collect; version="[31.0.0,32.0.0)"_    -> Export-Package: com.google.common.collect; bundle-symbolic-name="sw360-datahandler"; bundle-version="1.0.0"; version="31.0.1"; uses:="com.google.common.base"_       sw360-datahandler [1636]_         Unresolved requirement: Import-Package: com.fasterxml.jackson.annotation; version="[2.13.0,3.0.0)"_  Unresolved requirement: Import-Package: com.google.common.base; version="[31.0.0,32.0.0)"_    -> Export-Package: com.google.common.base; bundle-symbolic-name="sw360-datahandler"; bundle-version="1.0.0"; version="31.0.1"_ [Sanitized]
        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
2023-02-10 13:44:33.273 ERROR [Framework Event Dispatcher: Equinox Container: a96acafa-50ce-4ea7-8214-5b17f492173b][Framework:93] FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: sw360-importers [1638]_  Unresolved requirement: Import-Package: com.google.common.collect; version="[31.0.0,32.0.0)"_    -> Export-Package: com.google.common.collect; bundle-symbolic-name="sw360-datahandler"; bundle-version="1.0.0"; version="31.0.1"; uses:="com.google.common.base"_       sw360-datahandler [1636]_         Unresolved requirement: Import-Package: com.fasterxml.jackson.annotation; version="[2.13.0,3.0.0)"_  Unresolved requirement: Import-Package: com.google.common.base; version="[31.0.0,32.0.0)"_    -> Export-Package: com.google.common.base; bundle-symbolic-name="sw360-datahandler"; bundle-version="1.0.0"; version="31.0.1"_ [Sanitized]
        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
2023-02-10 13:44:33.278 ERROR [Framework Event Dispatcher: Equinox Container: a96acafa-50ce-4ea7-8214-5b17f492173b][Framework:93] FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: sw360-portlet [1640]_  Unresolved requirement: Import-Package: com.google.common.base; version="[31.0.0,32.0.0)"_    -> Export-Package: com.google.common.base; bundle-symbolic-name="sw360-datahandler"; bundle-version="1.0.0"; version="31.0.1"_       sw360-datahandler [1636]_         Unresolved requirement: Import-Package: com.fasterxml.jackson.annotation; version="[2.13.0,3.0.0)"_  Unresolved requirement: Import-Package: com.google.common.cache; version="[31.0.0,32.0.0)"_    -> Export-Package: com.google.common.cache; bundle-symbolic-name="sw360-datahandler"; bundle-version="1.0.0"; version="31.0.1"; uses:="com.google.common.base,com.google.common.collect,com.google.common.util.concurrent"_ [Sanitized]
        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
2023-02-10 13:44:33.490 INFO  [main][ModuleFrameworkImpl:2007] Started web bundles
2023-02-10 13:44:33.492 INFO  [main][ModuleFrameworkImpl:407] Navigate to Control Panel > Configuration > Gogo Shell and enter "lb" to see all bundles
2023-02-10 13:44:36.400 WARN  [main][SidecarManager:111] Liferay is configured to use Elasticsearch engine running in a child process of current process named as sidecar. Do NOT use sidecar in production. Sidecar is useful for development and demonstration purposes. Refer to the documentation for details on the limitations of sidecar. Remote Elasticsearch connections can be configured in the Control Panel.
2023-02-10 13:44:36.403 INFO  [main][Sidecar:99] Starting sidecar Elasticsearch
2023-02-10 13:44:36.715 INFO  [main][Sidecar:541] Sidecar Elasticsearch properties : {action.auto_create_index=false,bootstrap.memory_lock=false,bootstrap.system_call_filter=false,cluster.name=LiferayElasticsearchCluster,cluster.routing.allocation.disk.threshold_enabled=false,discovery.type=single-node,http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/,http.cors.enabled=true,http.host=_local_,http.port=9201,indices.breaker.total.use_real_memory=false,monitor.jvm.gc.enabled=false,node.data=true,node.ingest=true,node.master=true,node.name=liferay,node.store.allow_mmap=false,path.data=/opt/liferay-ce-portal-7.3.3-ga4/data/elasticsearch7/indices,path.home=/opt/liferay-ce-portal-7.3.3-ga4/elasticsearch7,path.logs=/opt/liferay-ce-portal-7.3.3-ga4/logs,path.repo=/opt/liferay-ce-portal-7.3.3-ga4/data/elasticsearch7/repo,thread_pool.write.queue_size=100,transport.type=netty4}
2023-02-10 13:44:40.669 INFO  [main][Sidecar:115] Sidecar Elasticsearch liferay is at 127.0.0.1:9201

```

I followed https://github.com/eclipse/sw360/blob/sw360-16.0.0-M1/scripts/docker-config/download_dependencies.sh
These are the libs I have deployed

![image](https://user-images.githubusercontent.com/4498415/218117935-9c36b5dc-18d6-4bc2-9a34-3dee48e9b7f6.png)


I am not sure what version is required for what lib. May I have your help?

**Comment by hoangnt2** [comment]
Hi @dineshr93, please refer to this document
https://www.eclipse.org/sw360/docs/deployment/upgrading/upgrade_version_sw360_15_to_16/

**Comment by dineshr93** [comment]
@AnkitKumar-786 can you close this is issue
