### ISSUE TITLE
Merge Components may fail in last step because of database update issue

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#208]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Monday Jan 22, 2018 at 09:59 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/723_

----

(Alex and me) When merging a component, the last write to the target may fail at last write of plain fields at:

https://github.com/sw360/sw360portal/blob/e90785fb89e584eb3094fbc002787ddf7bdc9570/backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java#L476

because of an update conflict when the releases are merged, but the components dataset is not retrieved again.

In the stack trace below merging releases is at rev 20 resulting in rev 21, then plain fields write following does not see rev 20 as latest, but Java code call is at that level.

```
2018-01-22 12:01:45 ERROR DatabaseConnector:180 - Document cannot be updated Component(id:1cfc47ff...)
 org.ektorp.UpdateConflictException: document update conflict: id: 1cfc47ff3694425ac5e98f23a2355d90 rev: 20-0fb05174942c3e1a559b1dd3eba9a27d
        at org.ektorp.impl.StdCouchDbConnector$9.error(StdCouchDbConnector.java:378)
        at org.ektorp.impl.StdCouchDbConnector$9.error(StdCouchDbConnector.java:364)
        at org.ektorp.http.RestTemplate.handleResponse(RestTemplate.java:126)
        at org.ektorp.http.RestTemplate.put(RestTemplate.java:47)
        at org.ektorp.impl.StdCouchDbConnector.update(StdCouchDbConnector.java:363)
        at org.eclipse.sw360.datahandler.couchdb.DatabaseConnector.update(DatabaseConnector.java:177)
        at org.ektorp.support.CouchDbRepositorySupport.update(CouchDbRepositorySupport.java:181)
        at org.eclipse.sw360.datahandler.db.ComponentDatabaseHandler.updateComponentInternal(ComponentDatabaseHandler.java:417)
        at org.eclipse.sw360.datahandler.db.ComponentDatabaseHandler.updateComponentCompletely(ComponentDatabaseHandler.java:593)
```

**Comment by lepokle** [comment]
Two steps have to be done:
1. Be sure that component is the current one when updating (or only update once)
1. Abort on any error so source component is not delete if anything before fails

**Comment by lepokle** [comment]
From discussion:
- we will always overwrite the release names to match the new component name
- we will display any errors with affected components and releases. It is not possible to easily fix errors automatically. See also #664 for a long term solution
- we will forcing to merge all source components and to retain all destination components. This was forced during error detection right now. The fix for this issue should do anything automatically.
