### ISSUE TITLE
License Info generation returns 500 when deselecting a lot of things

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#212]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Tuesday Jan 30, 2018 at 12:45 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/735_

----

Coming from projects detail, linked releases and projects with attempting to generate license info.

in the license info view when "opening" the files (clicking on the unfold rectangle) to see the licenses inside and then selecting and deselecting a lot, meaning make a lot of choices, because contrary generating license info is straight forward, then the application works and works and returns a 500 ...

stacktrace:

```
2018-01-30 15:00:06 ERROR SW360Assert:135 - Invalid null input!
 SW360Exception(why:null)
        at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:129)
        at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotNull(SW360Assert.java:43)
        at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotNull(SW360Assert.java:37)
        at org.eclipse.sw360.licenseinfo.LicenseInfoHandler.getLicenseInfoFile(LicenseInfoHandler.java:99)
        at org.eclipse.sw360.datahandler.thrift.licenseinfo.LicenseInfoService$Processor$getLicenseInfoFile.getResult(LicenseInfoService.java:481)
        at org.eclipse.sw360.datahandler.thrift.licenseinfo.LicenseInfoService$Processor$getLicenseInfoFile.getResult(LicenseInfoService.java:466)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.thrift.server.TServlet.doPost(TServlet.java:83)
2018-01-30 15:00:06 ERROR ProcessFunction:41 - Internal error processing getLicenseInfoFile
 SW360Exception(why:Invalid null input!)
        at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:136)
        at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:130)
        at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotNull(SW360Assert.java:43)
        at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotNull(SW360Assert.java:37)
        at org.eclipse.sw360.licenseinfo.LicenseInfoHandler.getLicenseInfoFile(LicenseInfoHandler.java:99)
        at org.eclipse.sw360.datahandler.thrift.licenseinfo.LicenseInfoService$Processor$getLicenseInfoFile.getResult(LicenseInfoService.java:481)
        at org.eclipse.sw360.datahandler.thrift.licenseinfo.LicenseInfoService$Processor$getLicenseInfoFile.getResult(LicenseInfoService.java:466)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
2018-01-30 15:00:06,424 ERROR ProjectPortlet:202 - Error getting LicenseInfo file for project with id c3bcbe4d779080d7e470399f6700fec9 and generator null
 org.apache.thrift.TApplicationException: Internal error processing getLicenseInfoFile
        at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
        at org.eclipse.sw360.datahandler.thrift.licenseinfo.LicenseInfoService$Client.recv_getLicenseInfoFile(LicenseInfoService.java:161)
        at org.eclipse.sw360.datahandler.thrift.licenseinfo.LicenseInfoService$Client.getLicenseInfoFile(LicenseInfoService.java:144)
        at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.downloadLicenseInfo(ProjectPortlet.java:180)
        at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.serveResource(ProjectPortlet.java:150)
        at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:122)
        at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:82)
        at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:116)
```

**Comment by mcjaeger** [comment]
solved by this https://github.com/eclipse/sw360/pull/347
