### ISSUE TITLE
Deployment and then waiting for liferay UI to respond takes long time

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/sw360#707]
Deployment and then waiting for liferay UI to respond takes an incredibly long amount of time (30+ min) 

These are the stacktraces thrown in the process:
```
java.lang.NullPointerException
sw360_1                | 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
sw360_1                | 	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
sw360_1                | 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
sw360_1                | 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
sw360_1                | 	at org.eclipse.sw360.portal.users.UserCache.get(UserCache.java:59)
sw360_1                | 	at org.eclipse.sw360.portal.users.UserCacheHolder.loadUserFromEmail(UserCacheHolder.java:74)
sw360_1                | 	at org.eclipse.sw360.portal.users.UserCacheHolder.loadUserFromEmail(UserCacheHolder.java:82)
sw360_1                | 	at org.eclipse.sw360.portal.users.UserCacheHolder.getCurrentUser(UserCacheHolder.java:54)
sw360_1                | 	at org.eclipse.sw360.portal.users.UserCacheHolder.getUserFromRequest(UserCacheHolder.java:90)
sw360_1                | 	at org.eclipse.sw360.portal.portlets.homepage.MySubscriptionsPortlet.doView(MySubscriptionsPortlet.java:62)
sw360_1                | 	at com.liferay.portal.kernel.portlet.LiferayPortlet.doDispatch(LiferayPortlet.java:303)
sw360_1                | 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:478)
sw360_1                | 	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291)
sw360_1                | 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:302)
sw360_1                | 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127)
sw360_1                | 	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58)
sw360_1                | 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124)
sw360_1                | 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71)
sw360_1                | 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
sw360_1                | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
sw360_1                | 2019-10-23 11:20:11.246 ERROR [http-nio-8080-exec-6][render_portlet_jsp:131] null
sw360_1                | java.lang.NullPointerException
sw360_1                | 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
sw360_1                | 	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
sw360_1                | 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
sw360_1                | 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
sw360_1                | 	at org.eclipse.sw360.portal.users.UserCache.get(UserCache.java:59)
sw360_1                | 	at org.eclipse.sw360.portal.users.UserCacheHolder.loadUserFromEmail(UserCacheHolder.java:74)
sw360_1                | 	at org.eclipse.sw360.portal.users.UserCacheHolder.loadUserFromEmail(UserCacheHolder.java:82)
sw360_1                | 	at org.eclipse.sw360.portal.users.UserCacheHolder.getCurrentUser(UserCacheHolder.java:54)
sw360_1                | 	at org.eclipse.sw360.portal.users.UserCacheHolder.getUserFromRequest(UserCacheHolder.java:90)
sw360_1                | 	at org.eclipse.sw360.portal.portlets.homepage.RecentComponentPortlet.doView(RecentComponentPortlet.java:57)
sw360_1                | 	at com.liferay.portal.kernel.portlet.LiferayPortlet.doDispatch(LiferayPortlet.java:303)
sw360_1                | 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:478)
sw360_1                | 	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291)
sw360_1                | 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:302)
sw360_1                | 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127)
sw360_1                | 	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58)
sw360_1                | 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124)
sw360_1                | 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71)
sw360_1                | 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
sw360_1                | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)

```
```

09:56:01.876 ERROR [http-nio-8080-exec-372][IncludeTag:128] Current URL /fossology/thrift generates exception: null
sw360_1                | java.nio.BufferOverflowException
sw360_1                |    at java.nio.Buffer.nextPutIndex(Buffer.java:521)
sw360_1                |    at java.nio.HeapCharBuffer.put(HeapCharBuffer.java:169)
sw360_1                |    at com.liferay.portal.kernel.io.OutputStreamWriter.write(OutputStreamWriter.java:119)
sw360_1                |    at com.liferay.portal.kernel.io.unsync.UnsyncPrintWriter.write(UnsyncPrintWriter.java:349)
sw360_1                |    at freemarker.ext.jsp.JspWriterAdapter.write(JspWriterAdapter.java:169)
sw360_1                |    at com.liferay.portal.kernel.io.unsync.UnsyncPrintWriter.write(UnsyncPrintWriter.java:349)
sw360_1                |    at org.apache.jasper.runtime.JspWriterImpl.write(JspWriterImpl.java:199)
sw360_1                |    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
sw360_1                |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
sw360_1                |    at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:64)
sw360_1                |    at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:202)
sw360_1                |    at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79)
sw360_1                |    at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53)
sw360_1                |    at com.liferay.taglib.util.IncludeTag.includePage(IncludeTag.java:401)
sw360_1                |    at com.liferay.taglib.util.IncludeTag.include(IncludeTag.java:377)
sw360_1                |    at com.liferay.taglib.util.IncludeTag.doInclude(IncludeTag.java:220)
sw360_1                |    at com.liferay.taglib.util.IncludeTag.doEndTag(IncludeTag.java:89)
sw360_1                |    at freemarker.ext.jsp.TagTransformModel$TagWriter.endEvaluation(TagTransformModel.java:400)
sw360_1                |    at freemarker.ext.jsp.TagTransformModel$TagWriter.afterBody(TagTransformModel.java:388)
sw360_1                |    at freemarker.core.Environment.visitAndTransform(Environment.java:427)
sw360_1                | 2019-10-23 09:56:01.877 ERROR [http-nio-8080-exec-372][PasswordModifiedFilter:62] java.lang.IllegalStateException: Cannot forward after response has been committed
sw360_1                | java.lang.IllegalStateException: Cannot forward after response has been committed
sw360_1                |    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:323)
sw360_1                |    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
sw360_1                |    at com.liferay.portal.servlet.DirectServletPathRegisterDispatcher.forward(DirectServletPathRegisterDispatcher.java:45)
sw360_1                |    at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.forward(DirectRequestDispatcherFactoryImpl.java:185)
sw360_1                |    at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:82)
sw360_1                |    at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.forward(ClassLoaderRequestDispatcherWrapper.java:45)
sw360_1                |    at com.liferay.portal.struts.StrutsUtil.forward(StrutsUtil.java:82)
sw360_1                |    at com.liferay.portal.struts.PortalRequestProcessor._internalModuleRelativeForward(PortalRequestProcessor.java:364)
sw360_1                |    at com.liferay.portal.struts.PortalRequestProcessor._processForward(PortalRequestProcessor.java:444)
sw360_1                |    at com.liferay.portal.struts.PortalRequestProcessor._process(PortalRequestProcessor.java:406)
sw360_1                |    at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:155)
sw360_1                |    at com.liferay.portal.internal.servlet.MainServlet.doPost(MainServlet.java:213)
sw360_1                |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
sw360_1                |    at com.liferay.portal.internal.servlet.MainServlet.service(MainServlet.java:639)
sw360_1                |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
sw360_1                |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
sw360_1                |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sw360_1                |    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
sw360_1                |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sw360_1                |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sw360_1                |    at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124)
sw360_1                |    at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
sw360_1                |    at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360_1                |    at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360_1                |    at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360_1                |    at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360_1                |    at com.liferay.portal.servlet.filters.secure.BaseAuthFilter.processFilter(BaseAuthFilter.java:360)
sw360_1                |    at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360_1                |    at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360_1                |    at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360_1                |    at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360_1                |    at com.liferay.portal.monitoring.internal.servlet.filter.MonitoringFilter.processFilter(MonitoringFilter.java:181)
sw360_1                |    at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360_1                |    at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360_1                |    at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360_1                |    at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:106)
sw360_1                |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sw360_1                |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sw360_1                |    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
sw360_1                |    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
sw360_1                |    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
sw360_1                |    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
sw360_1                |    at com.liferay.portal.util.PortalImpl.sendError(PortalImpl.java:6842)
sw360_1                |    at com.liferay.friendly.url.internal.servlet.FriendlyURLServlet.service(FriendlyURLServlet.java:364)
sw360_1                |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
sw360_1                |    at com.liferay.portal.servlet.ServletAdapter.service(ServletAdapter.java:99)
sw360_1                |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
sw360_1                |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
sw360_1                |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sw360_1                |    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
sw360_1                |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sw360_1                |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sw360_1                |    at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124)
sw360_1                |    at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360_1                |    at com.liferay.portal.servlet.filters.i18n.I18nFilter.processFilter(I18nFilter.java:370)
sw360_1                |    at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360_1                |    at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360_1                |    at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360_1                |    at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
sw360_1                |    at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360_1                |    at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360_1                |    at co
```

Here's a picture of the UI after waiting for 30 minutes for the UI to reload:
![sw360failure_3](https://user-images.githubusercontent.com/44478897/67389143-48672a00-f59a-11e9-8209-604a0147a7de.PNG)

**Comment by mcjaeger** [comment]
I think it was an issue of some version of the sw360chores deployment
