### ISSUE TITLE
NPE in ProjectDatabaseHandler.setReleaseRelatoins when importing with Antenna (PR-547)

### ISSUE THREAD

**Issue by kallesoranko** [eclipse/sw360#711]
```
sw360_1_c496c79b2859   | 2019-10-30 13:06:41 ERROR ProcessFunction:47 - Internal error processing updateProject
sw360_1_c496c79b2859   |  java.lang.NullPointerException
sw360_1_c496c79b2859   |        at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.setReleaseRelatoins(ProjectDatabaseHandler.java:230)
sw360_1_c496c79b2859   |        at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.updateProject(ProjectDatabaseHandler.java:211)
sw360_1_c496c79b2859   |        at org.eclipse.sw360.projects.ProjectHandler.updateProject(ProjectHandler.java:194)
sw360_1_c496c79b2859   |        at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$updateProject.getResult(ProjectService.java:2381)
sw360_1_c496c79b2859   |        at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$updateProject.getResult(ProjectService.java:2361)
sw360_1_c496c79b2859   |        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
sw360_1_c496c79b2859   |        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
sw360_1_c496c79b2859   |        at org.apache.thrift.server.TServlet.doPost(TServlet.java:83)
sw360_1_c496c79b2859   |        at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:42)
```

**Comment by kallesoranko** [comment]
There seems to be a spelling mistake also in the method name: `backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java:223`

**Comment by kallesoranko** [comment]
@akapti 
maybe the condition should be changed to `if (!(current != null || !current.getReleaseIdToUsage().isEmpty()) && isMainlineStateDisabled) {`
Any ideas?

**Comment by akapti** [comment]
@kallesoranko I have created a PR to fix this issue: https://github.com/eclipse/sw360/pull/712
Kindly test and let me know if NPE is fixed.

**Comment by kallesoranko** [comment]
Thanks for the quick reply. I'll test this right away
