### ISSUE TITLE
NPE in computeReleaseClearingStateSummary

### ISSUE THREAD

**Issue by kallesoranko** [eclipse/sw360#713]
When entering Project-portlet (main Projects view)`computeReleaseClearingStateSummary` fails with NPE at line 39 in ReleaseClearingStateSummaryComputer.

https://github.com/eclipse/sw360/blob/0122f1a21a90cba4c7690159ec48e46ef3f2bd4c/libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/businessrules/ReleaseClearingStateSummaryComputer.java#L38-L42

**Stacktrace:**
```
  2019-11-06 11:16:54 ERROR ProcessFunction:47 - Internal error processing fillClearingStateSummaryIncludingSubprojects
   java.lang.NullPointerException
         at org.eclipse.sw360.datahandler.businessrules.ReleaseClearingStateSummaryComputer.computeReleaseClearingStateSummary(ReleaseClearingStateSummaryComputer.java:39)
         at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.lambda$fillClearingStateSummaryIncludingSubprojects$3(ProjectDatabaseHandler.java:666)
         at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
         at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
         at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.fillClearingStateSummaryIncludingSubprojects(ProjectDatabaseHandler.java:657)
         at org.eclipse.sw360.projects.ProjectHandler.fillClearingStateSummaryIncludingSubprojects(ProjectHandler.java:253)
         at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$fillClearingStateSummaryIncludingSubprojects.getResult(ProjectService.java:2632)
         at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$fillClearingStateSummaryIncludingSubprojects.getResult(ProjectService.java:2612)
         at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
  2019-11-06 11:16:54.024 ERROR [http-nio-8080-exec-338][ProjectPortlet:1154] Could not get summary of release clearing states for projects and their subprojects!
  org.apache.thrift.TApplicationException: Internal error processing fillClearingStateSummaryIncludingSubprojects
         at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
         at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Client.recv_fillClearingStateSummaryIncludingSubprojects(ProjectService.java:905)
         at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Client.fillClearingStateSummaryIncludingSubprojects(ProjectService.java:891)
         at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.getWithFilledClearingStateSummaryIncludingSubprojects(ProjectPortlet.java:1152)
         at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.serveGetClearingStateSummaries(ProjectPortlet.java:449)
         at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.serveResource(ProjectPortlet.java:189)
         at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:146)
         at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:88)
         at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:140)
         at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:78)
         at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
         at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
         at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
         at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
         at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.forward(RequestDispatcherAdaptor.java:40)
         at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:569)
         at com.liferay.portlet.internal.InvokerPortletImpl.invokeResource(InvokerPortletImpl.java:695)
         at com.liferay.portlet.internal.InvokerPortletImpl.serveResource(InvokerPortletImpl.java:509)
         at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.serveResource(MonitoringInvokerPortlet.java:313)
         at com.liferay.portlet.internal.PortletContainerImpl._serveResource(PortletContainerImpl.java:1087)
         at com.liferay.portlet.internal.PortletContainerImpl.lambda$serveResource$4(PortletContainerImpl.java:270)
         at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:427)
         at com.liferay.portlet.internal.PortletContainerImpl.serveResource(PortletContainerImpl.java:263)
         at com.liferay.portlet.SecurityPortletContainerWrapper.serveResource(SecurityPortletContainerWrapper.java:212)
         at com.liferay.portlet.RestrictPortletContainerWrapper.serveResource(RestrictPortletContainerWrapper.java:157)
         at com.liferay.portal.kernel.portlet.PortletContainerUtil.serveResource(PortletContainerUtil.java:233)
         at com.liferay.portal.action.LayoutAction.processLayout(LayoutAction.java:394)
         at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:174)
         at com.liferay.portal.struts.PortalRequestProcessor._process(PortalRequestProcessor.java:415)
         at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:155)
         at com.liferay.portal.internal.servlet.MainServlet.doPost(MainServlet.java:213)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
         at com.liferay.portal.internal.servlet.MainServlet.service(MainServlet.java:639)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124)
         at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.servlet.filters.secure.BaseAuthFilter.processFilter(BaseAuthFilter.java:360)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.monitoring.internal.servlet.filter.MonitoringFilter.processFilter(MonitoringFilter.java:181)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:106)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
         at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
         at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
         at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
         at com.liferay.friendly.url.internal.servlet.FriendlyURLServlet.service(FriendlyURLServlet.java:398)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
         at com.liferay.portal.servlet.ServletAdapter.service(ServletAdapter.java:99)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.servlet.filters.i18n.I18nFilter.processFilter(I18nFilter.java:370)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.servlet.filters.secure.BaseAuthFilter.processFilter(BaseAuthFilter.java:360)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.servlet.filters.etag.ETagFilter.processFilter(ETagFilter.java:89)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.servlet.filters.autologin.AutoLoginFilter.processFilter(AutoLoginFilter.java:266)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.processFilter(VirtualHostFilter.java:266)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.monitoring.internal.servlet.filter.MonitoringFilter.processFilter(MonitoringFilter.java:181)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
         at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
         at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
         at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
         at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
         at com.liferay.portal.servlet.filters.urlrewrite.UrlRewriteFilter.processFilter(UrlRewriteFilter.java:65)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:175)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:175)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:106)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
         at java.lang.Thread.run(Thread.java:748)
```
I am using current master at `2027eaa1cccb8d0f4fa50300b3aebc8cbdded014`

**Comment by neubs-bsi** [comment]
I was working on my local instance and encountered the bellow error message after the one in this issue. Are they related or does this require a new issue? 

```
sw360_1                | java.lang.NullPointerException
sw360_1                | 	at org.eclipse.sw360.datahandler.common.SW360Utils.getApprovedClxAttachmentForRelease(SW360Utils.java:246)
sw360_1                | 	at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.lambda$addLicenseInfos$32(ProjectPortlet.java:1503)
sw360_1                | 	at java.util.ArrayList.forEach(ArrayList.java:1257)
sw360_1                | 	at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.addLicenseInfos(ProjectPortlet.java:1502)
sw360_1                | 	at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.putLinkedObligations(ProjectPortlet.java:1490)
sw360_1                | 	at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.prepareDetailView(ProjectPortlet.java:956)
sw360_1                | 	at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.doView(ProjectPortlet.java:829)
sw360_1                | 	at com.liferay.portal.kernel.portlet.LiferayPortlet.doDispatch(LiferayPortlet.java:303)
sw360_1                | 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:478)
sw360_1                | 	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291)
sw360_1                | 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:302)
sw360_1                | 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127)
sw360_1                | 	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58)
sw360_1                | 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124)
sw360_1                | 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71)
sw360_1                | 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
sw360_1                | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
sw360_1                | 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
sw360_1                | 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
sw360_1                | 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
```

**Comment by kallesoranko** [comment]
> Are they related or does this require a new issue?

Which branch/commit are you working with? I guess the issue you are facing is same as https://github.com/eclipse/sw360/issues/719 and it was fixed via https://github.com/eclipse/sw360/pull/721. Maybe you have an older version?

**Comment by neubs-bsi** [comment]
Ah perfect, thanks. That is it. 
I was working on a slightly older version.
