### ISSUE TITLE
NPE in SW360Utils.getApprovedClxAttachmentForRelease

### ISSUE THREAD

**Issue by kallesoranko** [eclipse/sw360#719]
NPE at line 246

https://github.com/eclipse/sw360/blob/0158733a5a6420c093ca728447b61cb81edc1cf3/libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java#L245-L249

```
 2019-11-06 15:08:55.308 ERROR [http-nio-8080-exec-18][render_portlet_jsp:131] null
 java.lang.NullPointerException
        at org.eclipse.sw360.datahandler.common.SW360Utils.getApprovedClxAttachmentForRelease(SW360Utils.java:246)
        at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.lambda$addLicenseInfos$32(ProjectPortlet.java:1503)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.addLicenseInfos(ProjectPortlet.java:1502)
        at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.putLinkedObligations(ProjectPortlet.java:1490)
        at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.prepareDetailView(ProjectPortlet.java:956)
        at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.doView(ProjectPortlet.java:829)
        at com.liferay.portal.kernel.portlet.LiferayPortlet.doDispatch(LiferayPortlet.java:303)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:478)
        at javax.portlet.GenericPortlet.render(GenericPortlet.java:291)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:302)
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127)
        at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58)
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124)
        at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71)
        at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
```

**Comment by akapti** [comment]
I am working on this.

**Comment by kallesoranko** [comment]
@akapti Great 👍
