### ISSUE TITLE
Detail page of License is can not be opened

### ISSUE THREAD

**Issue by realasgard** [eclipse/sw360#817]
Hi.

**Phenomenon**
In SW360's License page, some Licenses can not be checked detail.
When I click "License Shortname" link.
![screenshot_02](https://user-images.githubusercontent.com/50013912/77611283-48fc5600-6f68-11ea-8848-3aa342978632.png)

And below messages are shown in catalina.out
> 2020-03-26 04:53:50 ERROR ProcessFunction:47 - Internal error processing getByIDWithOwnModerationRequests
>  java.lang.NullPointerException
>         at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
>         at com.google.common.collect.SingletonImmutableSet.<init>(SingletonImmutableSet.java:47)
>         at com.google.common.collect.ImmutableSet.of(ImmutableSet.java:82)
>         at com.google.common.collect.ImmutableSet.construct(ImmutableSet.java:164)
>         at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:267)
>         at org.eclipse.sw360.datahandler.couchdb.DatabaseConnector.get(DatabaseConnector.java:164)
>         at org.eclipse.sw360.datahandler.couchdb.DatabaseConnector.get(DatabaseConnector.java:176)
>         at org.eclipse.sw360.datahandler.couchdb.DatabaseRepository.get(DatabaseRepository.java:209)
>         at org.eclipse.sw360.licenses.db.LicenseDatabaseHandler.getTodosByIds(LicenseDatabaseHandler.java:707)
> 2020-03-26 04:53:50.684 ERROR [http-nio-8080-exec-4][LicensesPortlet:215] Error fetching license details for id 0BSD from backend
> org.apache.thrift.TApplicationException: Internal error processing getByIDWithOwnModerationRequests
>         at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
>         at org.eclipse.sw360.datahandler.thrift.licenses.LicenseService$Client.recv_getByIDWithOwnModerationRequests(LicenseService.java:474)
>         at org.eclipse.sw360.datahandler.thrift.licenses.LicenseService$Client.getByIDWithOwnModerationRequests(LicenseService.java:459)
>         at org.eclipse.sw360.portal.portlets.licenses.LicensesPortlet.prepareDetailView(LicensesPortlet.java:189)
>         at org.eclipse.sw360.portal.portlets.licenses.LicensesPortlet.doView(LicensesPortlet.java:119)
>         at com.liferay.portal.kernel.portlet.LiferayPortlet.doDispatch(LiferayPortlet.java:286)
>         at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:485)

**Conditions**
- There is "todoDatabaseIds" field in the license data
- And, it contains invalid todoDatabaseId. For example deleted id or null. 
> "todoDatabaseIds": [
>        "hogehoge" <- invalid id
>    ]

![license_error_02](https://user-images.githubusercontent.com/50013912/77627797-c769ef80-6f8a-11ea-8e11-c25c00d40666.png)

> "todoDatabaseIds": [
>        null
>    ]

![license_error_01](https://user-images.githubusercontent.com/50013912/77627781-bfaa4b00-6f8a-11ea-968d-e909e655b52b.png)

- If there is no "todoDatabaseIds" itself, no problem
- If "todoDatabaseIds" is empty list, no problem
> "todoDatabaseIds": [
>    ]

**Measure**
- fix Editor of License data
I don't know which functions create these invalid data.
But when todo is deleted by admin page, id in todoDatabaseIds is not erased.
It become invalid.
- fix Viewer of License data
I use below code in my system for solving this issue.
[my patch](https://github.com/realasgard/sw360/commit/7aabe8083df8bafb54b202f1578fb22dcb145d99)
these codes ignore invalid todo's id when system load todos.
What do you think this patch?

**Comment by mcjaeger** [comment]
hm it could be a bug, but could you pls let us know how you have added the license?

**Comment by realasgard** [comment]
I found these invalid data in my instance. But I don't know how these are generated.
I though it was better to fix only the loading code.
But if no one is bothered by this issue, you don't need to spend your time.
Thank you.

**Comment by mcjaeger** [comment]
it was not meant this way, we nee to spend our time the point is only that it runs our instances.
Did you consider this at updating?

https://github.com/eclipse/sw360/tree/master/scripts/migrations

**Comment by mcjaeger** [comment]
that said, maybe you need to execute: https://github.com/eclipse/sw360/blob/master/scripts/migrations/012_migrate_todoid_to_title.py

**Comment by mcjaeger** [comment]
I have tested now it on on the multi language branch. I think, if a license is created there and then reopened it works. could be that the migration script is missing.

**Comment by mcjaeger** [comment]
@realasgard did the migration script work?

**Comment by realasgard** [comment]
@mcjaeger Thank you for your proposal.
I deployed my instance with 5.1.0. After that it's updated to 8.0.1. So I only use 014, 015, 016 migrattion scripts at that time.
And now I executed 012_migrate_todoid_to title.py. But there was no particular effect.
Maybe, this script manipulate "todo" data only, don't touch "license" data.
