### ISSUE TITLE
Running SW360ResourceServer main does not work with Java 11

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/sw360#967]
When I am trying to run the main function in the SW360ResourceServer class I get the following exception

```
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:93)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:56)
	at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:140)
	at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:546)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartingEvent(RestartApplicationListener.java:67)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:292)
	at org.eclipse.sw360.rest.resourceserver.Sw360ResourceServer.main(Sw360ResourceServer.java:90)

```

After a little research I found out that this might be due to the spring boot version SW360 is using. 
(https://stackoverflow.com/questions/52385610/java-class-cast-exception-spring-boot)

It seems that Class Loaders of spring boot versions lower than 2.1 do not support Java 11. 

It might be time to upgrade the spring boot version as being able to run the main function in the SW360ResourceServer class is very helpful when testing code.

**Comment by mcjaeger** [comment]
we have had springboot 2.1 at that time. Wondering what that was. (because PR was merged earlier: https://github.com/eclipse/sw360/pull/916)
