### ISSUE TITLE
User search failed

### ISSUE THREAD

**Issue by AlbertHJY** [eclipse/sw360#991]
Failed to search user in release Contributors and Moderators

```
2020-09-22 06:50:14 INFO  LuceneAwareDatabaseConnector:129 - Trying to call lucene directly
2020-09-22 06:50:15 ERROR LuceneAwareDatabaseConnector:134 - Error querying Lucene directly.
java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "pathElement" is null
	at org.ektorp.http.URI.append(URI.java:56) ~[org.ektorp-1.5.0.jar:?]
	at org.eclipse.sw360.datahandler.couchdb.lucene.LuceneAwareDatabaseConnector.callLuceneDirectly(LuceneAwareDatabaseConnector.java:144) ~[datahandler-11.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.couchdb.lucene.LuceneAwareDatabaseConnector.searchView(LuceneAwareDatabaseConnector.java:131) [datahandler-11.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.couchdb.lucene.LuceneAwareDatabaseConnector.searchIds(LuceneAwareDatabaseConnector.java:101) [datahandler-11.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.couchdb.lucene.LuceneAwareDatabaseConnector.searchView(LuceneAwareDatabaseConnector.java:94) [datahandler-11.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.db.UserSearchHandler.searchByNameAndEmail(UserSearchHandler.java:56) [src-common-11.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.users.db.UserDatabaseHandler.searchUsers(UserDatabaseHandler.java:90) [src-users-11.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.users.UserHandler.searchUsers(UserHandler.java:74) [src-users-11.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$searchUsers.getResult(UserService.java:859) [datahandler-11.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$searchUsers.getResult(UserService.java:839) [datahandler-11.0.0-SNAPSHOT.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) [libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) [libthrift-0.13.0.jar:0.13.0]
	at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) [src-common-11.0.0-SNAPSHOT.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by mcjaeger** [comment]
Is merged to master, but I propose to keep it open until next tag

**Comment by mcjaeger** [comment]
search seem to work for me on current master
